openapi: 3.0.1
info:
  title: Kafka Swagger API
  description: Demo to simulate live chat API calls
  version: 1.0.0
servers:
  - url: http://localhost:7000
paths:
  /client-produce-message:
    post:
      summary: Produce a client message
      parameters:
        - name: message
          in: query
          description: Message to send
          required: true
          schema:
            type: string
        - name: dummy param
          in: query
          description: Some dummy param
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Message sent successfully
  /client-consume-message:
    get:
      summary: Consume client message
      responses:
        "200":
          description: Message consumed
          content:
            text/plain:
              schema:
                type: string
