openapi: 3.0.1
info:
  title: Kafka Swagger API
  description: Demo to simulate live chat API calls
  version: 1.0.0
servers:
  - url: http://localhost:7000

tags:
  - name: Client API
    description: Operations related to clients
  - name: Admin API
    description: Operations related to staff/devs
paths:
  /client-produce-message:
    post:
      summary: Produce a client message
      tags:
        - Client API
      parameters:
        - name: message
          in: query
          description: Message to send
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Message sent successfully
  /client-consume-message:
    get:
      summary: Consume client message
      tags:
        - Client API
      responses:
        "200":
          description: Message consumed
          content:
            text/plain:
              schema:
                type: string



  /admin-add-banned-word:
    post:
      summary: Add a new banned word to a dedicated topic
      tags:
        - Admin API
      parameters:
        - name: topic
          in: query
          description: Dedicated topic for banned words
          required: true
          schema:
            type: string
        - name: word
          in: query
          description: Word to add
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Banned word added successfully

  /admin-remove-banned-word:
    post:
      summary: Remove a new banned word from a dedicated topic
      tags:
        - Admin API
      parameters:
        - name: topic
          in: query
          description: Dedicated topic for banned words
          required: true
          schema:
            type: string
        - name: word
          in: query
          description: Word to remove
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Banned word removed successfully

