openapi: 3.0.1
info:
  title: Kafka Swagger API
  description: Demo to simulate live chat API calls
  version: 1.0.0
servers:
  - url: http://localhost:7000

tags:
  - name: Client API
    description: Operations related to clients
  - name: Admin API
    description: Operations related to staff/devs
paths:
  /client/produce:
    post:
      summary: Produce a client message
      tags:
        - Client API
      parameters:
        - name: channel
          in: query
          description: Channel name
          required: true
          schema:
            type: string
        - name: username
          in: query
          description: Your username
          required: true
          schema:
            type: string
        - name: message
          in: query
          description: Message to send
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Message sent successfully
  /client/consume:
    post:
      summary: Consume client message
      tags:
        - Client API
      parameters:
        - name: channel
          in: query
          description: Channel to consume from
          required: true
          schema:
            type: string
        - name: username
          in: query
          description: Your username
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Messages consumed successfully



  /admin/ban-word:
    post:
      summary: Add a new banned word to a dedicated topic
      tags:
        - Admin API
      parameters:
        - name: topic
          in: query
          description: Dedicated topic for banned words
          schema:
            type: string
            default: banned-words
        - name: word
          in: query
          description: Word to add
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Banned word added successfully

  /admin/unban-word:
    post:
      summary: Remove a new banned word from a dedicated topic
      tags:
        - Admin API
      parameters:
        - name: topic
          in: query
          description: Dedicated topic for banned words
          schema:
            type: string
            default: banned-words
        - name: word
          in: query
          description: Word to remove
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Banned word removed successfully

